#!/bin/bash
PUPPETDIR=/puppet/testrepo
cd ${PUPPETDIR}
git fetch origin
if git diff origin master ; then
   git fetch --all
   git reset --hard origin/master
   git pull origin master
   puppet apply /puppet/testrepo/manifests/nodes.pp --hiera_config=/puppet/testrepo/hiera.yaml
fi
