#!/bin/bash
cd /puppet/testrepo
git fetch --all 
git reset --hard origin/master
git pull origin master
chmod 700 set-services

cp -r /puppet/testrepo/modules/* /etc/puppet/modules
ln -s /puppet/testrepo/ /etc/puppet/modules/galera/
echo 'user localhost=(root) NOPASSWD: /sbin/iptables -vnxL' >> /etc/sudoers
puppet apply /puppet/testrepo/manifests/nodes.pp --hiera_config=/puppet/testrepo/hiera.yaml

if hostname | grep ^node* > /dev/true; then
  service xinetd start
fi

crontab -l > pullcron
echo "*/10 * * * * /puppet/testrepo/pull-updates" >> pullcron
crontab pullcron
rm pullcron
